### ISSUE TITLE
Enlace a `estrategias y consejos` devuelve 404

### ISSUE THREAD

**Issue by sebastinez** [FreeCodeCampBA/quick-start#5]
El enlace en el punto `Problemas algorítmicos? Leé algunas estrategias y consejos para resolverlos.` que apunta a `https://nicolasquiroz.com/problem-solving-strategies/` devuelve un 404.

**Comment by nhsz** [comment]
Gracias por avisar! Lo removí porque ya no tengo hosteado ese proyecto. Saludos!
